# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Extra settings merged into OpenTelemetry Collector configuration
# Adds X-Ray OTLP endpoint for traces alongside existing Jaeger exporter
# Adds CloudWatch OTLP endpoint for metrics (granite pre-prod)

extensions:
  sigv4auth:
    region: us-east-1
    service: xray
  sigv4auth/xray-beta:
    region: us-west-2
    service: xray
  sigv4auth/metrics:
    region: us-east-1
    service: monitoring

exporters:
  otlphttp/xray:
    endpoint: https://xray.us-east-1.amazonaws.com
    auth:
      authenticator: sigv4auth
  otlphttp/xray-beta:
    endpoint: https://xray-beta.us-west-2.amazonaws.com
    auth:
      authenticator: sigv4auth/xray-beta
  otlphttp/cloudwatch-metrics:
    endpoint: https://granite.amazonaws.com
    compression: gzip
    auth:
      authenticator: sigv4auth/metrics

service:
  extensions: [sigv4auth, sigv4auth/xray-beta, sigv4auth/metrics]
  pipelines:
    traces:
      exporters: [otlp_grpc/jaeger, spanmetrics, otlphttp/xray, otlphttp/xray-beta, debug]
    metrics:
      exporters: [otlp_http/prometheus, debug, otlphttp/cloudwatch-metrics]
